name: <+serviceVariables.JOB_NAME>
namespace: <+serviceVariables.NAMESPACE>
image: us-east1-docker.pkg.dev/dv01-231516/dv01/intelligence:master-7be8a433
envVars: <+serviceVariables.ENV_VARS>
schedule: <+serviceVariables.SCHEDULE>
command: <+serviceVariables.COMMAND>
resources:
  limits:
    cpu: <+serviceVariables.CPU_LIMIT>
    memory: <+serviceVariables.MEMORY_LIMIT>
  requests:
    cpu: <+serviceVariables.CPU_REQUEST>
    memory: <+serviceVariables.MEMORY_REQUEST>
serviceAccount: <+serviceVariables.SERVICE_ACCOUNT>
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: Never