apiVersion: batch/v1
kind: Job
metadata:
  name: oracledeployment
  namespace: steady-state
spec: 
  template:
    metadata:
      name:  oracledeployment
    spec:
      containers:
      - name:  oracledeployment
        image: nginx:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Never
  backoffLimit: 0
