apiVersion: batch/v1
kind: Job
metadata:
  name: sampledeployment
  namespace: steady-state
spec: 
  template:
    metadata:
      name:  sampledeployment
    spec:
      containers:
      - name:  sampledeployment
        image: nginx:latest
        imagePullPolicy: Always
        resources: 
          limits:
            cpu: "1"
            memory: "1Gi"
      restartPolicy: Never
  backoffLimit: 0
