image: eahrend/cron:latest
name: foobarbaz
imagePullPolicy: Always
envVars: <+configFile.getAsString("v1")>
schedule: "* * * * *"
command: |-
  /usr/local/bin/secrets-init
  --provider=google
  /bin/bash
  /usr/bin/start-server.sh
  /usr/bin/R
  -e
  "setwd('/tmp/dv01.intelligence/'); library(dv01.intelligence); dv01.intelligence::score_matches(environment=prod)"
serviceAccount: "intelligence-api"
resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 256Mi
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 3
concurrencyPolicy: Forbid
restartPolicy: Never
nodeSelector:
  type: infra
